eureka:
 client:
  serviceUrl:
# defaultZone提供这个服务的地址
   defaultZone: http://localhost:8081/eureka/
 instance:
  matadataMap:
   zone: zone1
 client:
  preferSameZoneEureka: true
 instance:
  matadataMap:
   zone: zone2
 client:
  preferSameZoneEureka: true