server:
 port: 8082
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8080/eureka/
# 配置config server的git仓库
spring:
 application:
  name: config
 cloud: 
  label: master
  config:
   server:
    git:
     uri: https://github.com/zuiliushang/spring-cloud-learn/
     searchPaths: config-repo